#!/usr/bin/env bash
set -Eeuo pipefail

# SwiftCart — Day 2: Global Edge Delivery, Unified Routing & Persistent Storage
# Region: ap-southeast-2 (Sydney)
# Builds on Day 1.
#
# Provisions:
#   - Private S3 static-assets bucket + index.html
#   - CloudFront: S3/OAC default origin + ALB dynamic origin
#   - EFS shared storage for Web Portal in VPC A (AZ a + AZ b)
#   - 50 GiB gp3 / 3000 IOPS / 125 MB/s EBS for Inventory
#   - Optional Linux mounts through the Day 1 Bastion
#
# IMPORTANT:
#   Run with Bash, NOT sh:
#     chmod +x ./swiftcart-day2-provision-ap-southeast-2-fixed-v8.sh
#     ./swiftcart-day2-provision-ap-southeast-2-fixed-v8.sh
#
# CloudFront account verification:
#   If AWS rejects CreateDistribution with "account must be verified", this
#   script does NOT abort. It continues with S3/EFS/EBS and leaves CloudFront
#   pending. Rerun after AWS verifies the account.
#
# Optional environment overrides:
#   REGION, KEY_NAME, NOTIFY_EMAIL, SKIP_CLOUDFRONT, WAIT_CLOUDFRONT,
#   DO_OS_MOUNTS, ASSUME_YES, STATE_FILE, S3_BUCKET
# =============================================================================

REGION="${REGION:-ap-southeast-2}"
# Force all regional AWS CLI operations to use Sydney, even if the local AWS CLI
# profile/environment was previously configured for another region.
export AWS_REGION="$REGION"
export AWS_DEFAULT_REGION="$REGION"
PROJECT="SwiftCart"
KEY_NAME="${KEY_NAME:-swiftcart-key}"
NOTIFY_EMAIL="${NOTIFY_EMAIL:-devopsbyraham@gmail.com}"
SKIP_CLOUDFRONT="${SKIP_CLOUDFRONT:-false}"
WAIT_CLOUDFRONT="${WAIT_CLOUDFRONT:-false}"
DO_OS_MOUNTS="${DO_OS_MOUNTS:-true}"
ASSUME_YES="${ASSUME_YES:-false}"
STATE_FILE="${STATE_FILE:-./swiftcart-day2-state.env}"
S3_BUCKET="${S3_BUCKET:-}"

TMP_DIR="${TMPDIR:-/tmp}/swiftcart-day2"
mkdir -p "$TMP_DIR"

log()  { printf '\033[1;34m[INFO]\033[0m %s\n' "$*"; }
ok()   { printf '\033[1;32m[ OK ]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[WARN]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m[FAIL]\033[0m %s\n' "$*" >&2; exit 1; }

trap 'printf "\033[1;31m[FAIL]\033[0m Day 2 stopped at line %s.\n" "$LINENO" >&2' ERR

command -v aws >/dev/null 2>&1 || die "AWS CLI is required."
command -v ssh >/dev/null 2>&1 || true
command -v sed >/dev/null 2>&1 || die "sed is required."

aws sts get-caller-identity >/dev/null 2>&1 || die "AWS credentials are invalid or missing."

ACCOUNT_ID="$(aws sts get-caller-identity --query Account --output text)"
CALLER_ARN="$(aws sts get-caller-identity --query Arn --output text)"
AZ1="${REGION}a"
AZ2="${REGION}b"

log "Account : $ACCOUNT_ID"
log "Caller  : $CALLER_ARN"
log "Region  : $REGION"
log "AZs     : $AZ1 / $AZ2"

# ----------------------------------------------------------------------------
# State helpers
# ----------------------------------------------------------------------------
record() {
  local key="$1" value="${2:-}" escaped
  escaped="$(printf '%q' "$value")"
  touch "$STATE_FILE"
  if grep -qE "^${key}=" "$STATE_FILE" 2>/dev/null; then
    awk -v k="$key" -v v="$escaped" 'BEGIN{FS=OFS="="} $1==k {$0=k"="v} {print}' \
      "$STATE_FILE" > "${STATE_FILE}.tmp"
    mv "${STATE_FILE}.tmp" "$STATE_FILE"
  else
    printf '%s=%s\n' "$key" "$escaped" >> "$STATE_FILE"
  fi
}

load_state() {
  [[ -f "$STATE_FILE" ]] || return 0
  # State is generated by this script with printf %q.
  # shellcheck disable=SC1090
  source "$STATE_FILE"
}

# Prefer an explicitly supplied Day 2 state file, otherwise import Day 1 state.
load_state

for day1_state in ./swiftcart-state.env ./swiftcart-day1-state.env "$HOME/swiftcart-state.env"; do
  if [[ -f "$day1_state" ]]; then
    # shellcheck disable=SC1090
    source "$day1_state"
    log "Loaded Day 1 state: $day1_state"
    break
  fi
done

# ----------------------------------------------------------------------------
# AWS lookup helpers
# ----------------------------------------------------------------------------
first_or_empty() {
  local value="$1"
  [[ "$value" == "None" || "$value" == "null" ]] && value=""
  printf '%s' "$value"
}

# AWS CLI waiter commands are not available in every installed CLI build.
# Poll resource state directly so the script works across AWS CLI versions.
wait_efs_available() {
  local fs_id="$1" state i
  for i in $(seq 1 60); do
    state="$(aws efs describe-file-systems --region "$REGION" --file-system-id "$fs_id" --query 'FileSystems[0].LifeCycleState' --output text 2>/dev/null || true)"
    state="$(first_or_empty "$state")"
    [[ "$state" == "available" ]] && return 0
    [[ "$state" == "deleting" || "$state" == "deleted" ]] && return 1
    sleep 2
  done
  return 1
}

wait_efs_mount_target_available() {
  local mt_id="$1" state i
  for i in $(seq 1 90); do
    state="$(aws efs describe-mount-targets --region "$REGION" --mount-target-id "$mt_id" --query 'MountTargets[0].LifeCycleState' --output text 2>/dev/null || true)"
    state="$(first_or_empty "$state")"
    [[ "$state" == "available" ]] && return 0
    [[ "$state" == "error" || "$state" == "deleting" || "$state" == "deleted" ]] && return 1
    sleep 2
  done
  return 1
}

wait_volume_state() {
  local volume_id="$1" desired="$2" state i
  for i in $(seq 1 60); do
    state="$(aws ec2 describe-volumes --region "$REGION" --volume-ids "$volume_id" --query 'Volumes[0].State' --output text 2>/dev/null || true)"
    state="$(first_or_empty "$state")"
    [[ "$state" == "$desired" ]] && return 0
    [[ "$state" == "error" || "$state" == "deleted" ]] && return 1
    sleep 2
  done
  return 1
}

wait_cloudfront_deployed() {
  local dist_id="$1" status i
  for i in $(seq 1 180); do
    status="$(aws cloudfront get-distribution --id "$dist_id" --query 'Distribution.Status' --output text 2>/dev/null || true)"
    status="$(first_or_empty "$status")"
    [[ "$status" == "Deployed" ]] && return 0
    sleep 10
  done
  return 1
}

# Resolve a subnet reliably even when the Day 1 state file is stale or the
# Name tag differs from the expected value. We first use the Name tag, then
# fall back to the exact VPC + CIDR + AZ combination. If the subnet is truly
# missing, we create the Day 1-required subnet so Day 2 can continue.
resolve_subnet() {
  # resolve_subnet <vpc-id> <name-tag> <cidr> <az>
  local vpc="$1" name="$2" cidr="$3" az="$4" id=""

  id="$(aws ec2 describe-subnets \
    --filters "Name=vpc-id,Values=$vpc" "Name=tag:Name,Values=$name" \
    --query 'Subnets[0].SubnetId' --output text 2>/dev/null || true)"
  id="$(first_or_empty "$id")"

  if [[ -z "$id" ]]; then
    id="$(aws ec2 describe-subnets \
      --filters "Name=vpc-id,Values=$vpc" "Name=cidr-block,Values=$cidr" "Name=availability-zone,Values=$az" \
      --query 'Subnets[0].SubnetId' --output text 2>/dev/null || true)"
    id="$(first_or_empty "$id")"
  fi

  if [[ -z "$id" ]]; then
    log "Day 1 subnet $name ($cidr / $az) is missing; creating it now."
    id="$(aws ec2 create-subnet \
      --vpc-id "$vpc" \
      --cidr-block "$cidr" \
      --availability-zone "$az" \
      --tag-specifications "ResourceType=subnet,Tags=[{Key=Name,Value=$name},{Key=Project,Value=$PROJECT}]" \
      --query 'Subnet.SubnetId' --output text)"
    id="$(first_or_empty "$id")"
  fi

  [[ -n "$id" ]] || die "Unable to resolve or create subnet '$name' ($cidr in $az)."
  printf '%s' "$id"
}

# ----------------------------------------------------------------------------
# Resolve Day 1 resources. Stable names are used if state is unavailable.
# ----------------------------------------------------------------------------
VPC_A="${VPC_A:-}"
VPC_B="${VPC_B:-}"
SUB_A_PUB_1A="${SUB_A_PUB_1A:-}"
SUB_A_PUB_1B="${SUB_A_PUB_1B:-}"
SUB_B_PRV_1A="${SUB_B_PRV_1A:-}"
SG_WEB="${SG_WEB:-}"
SG_BASTION="${SG_BASTION:-}"
EC2_BASTION="${EC2_BASTION:-}"
EC2_WEB="${EC2_WEB:-}"
EC2_INV="${EC2_INV:-}"
ALB_DNS="${ALB_DNS:-}"
ALB_ARN="${ALB_ARN:-}"

if [[ -z "$VPC_A" ]]; then
  VPC_A="$(aws ec2 describe-vpcs \
    --filters "Name=tag:Name,Values=$PROJECT-VPC-A-Public" \
    --query 'Vpcs[0].VpcId' --output text 2>/dev/null || true)"
  VPC_A="$(first_or_empty "$VPC_A")"
fi

if [[ -z "$VPC_B" ]]; then
  VPC_B="$(aws ec2 describe-vpcs \
    --filters "Name=tag:Name,Values=$PROJECT-VPC-B-Private" \
    --query 'Vpcs[0].VpcId' --output text 2>/dev/null || true)"
  VPC_B="$(first_or_empty "$VPC_B")"
fi

[[ -n "$VPC_A" ]] || die "Day 1 VPC A not found. Run Day 1 first."
[[ -n "$VPC_B" ]] || die "Day 1 VPC B not found. Run Day 1 first."

if [[ -z "$SUB_A_PUB_1A" ]]; then
  SUB_A_PUB_1A="$(aws ec2 describe-subnets \
    --filters "Name=vpc-id,Values=$VPC_A" "Name=tag:Name,Values=VPC-A-Public-Subnet-1a" \
    --query 'Subnets[0].SubnetId' --output text 2>/dev/null || true)"
  SUB_A_PUB_1A="$(first_or_empty "$SUB_A_PUB_1A")"
fi

if [[ -z "$SUB_A_PUB_1B" ]]; then
  SUB_A_PUB_1B="$(aws ec2 describe-subnets \
    --filters "Name=vpc-id,Values=$VPC_A" "Name=tag:Name,Values=VPC-A-Public-Subnet-1b" \
    --query 'Subnets[0].SubnetId' --output text 2>/dev/null || true)"
  SUB_A_PUB_1B="$(first_or_empty "$SUB_A_PUB_1B")"
fi

# IMPORTANT: Do not trust a stale SUB_B_PRV_1A from a previous state file.
# Validate it belongs to VPC B and is the expected 10.20.1.0/24 subnet in AZ-a.
if [[ -n "$SUB_B_PRV_1A" ]]; then
  VALID_SUBNET="$(aws ec2 describe-subnets \
    --subnet-ids "$SUB_B_PRV_1A" \
    --query "Subnets[?VpcId=='$VPC_B' && CidrBlock=='10.20.1.0/24' && AvailabilityZone=='$AZ1'].SubnetId | [0]" \
    --output text 2>/dev/null || true)"
  VALID_SUBNET="$(first_or_empty "$VALID_SUBNET")"
  [[ -n "$VALID_SUBNET" ]] || SUB_B_PRV_1A=""
fi

SUB_B_PRV_1A="$(resolve_subnet \
  "$VPC_B" \
  "VPC-B-Private-Subnet-1a" \
  "10.20.1.0/24" \
  "$AZ1")"

if [[ -z "$SG_WEB" ]]; then
  SG_WEB="$(aws ec2 describe-security-groups \
    --filters "Name=vpc-id,Values=$VPC_A" "Name=group-name,Values=SG-WebPortal" \
    --query 'SecurityGroups[0].GroupId' --output text 2>/dev/null || true)"
  SG_WEB="$(first_or_empty "$SG_WEB")"
fi

if [[ -z "$SG_BASTION" ]]; then
  SG_BASTION="$(aws ec2 describe-security-groups \
    --filters "Name=vpc-id,Values=$VPC_A" "Name=group-name,Values=SG-BastionHost" \
    --query 'SecurityGroups[0].GroupId' --output text 2>/dev/null || true)"
  SG_BASTION="$(first_or_empty "$SG_BASTION")"
fi

[[ -n "$SUB_A_PUB_1A" ]] || die "Day 1 VPC A public subnet 1a not found."
[[ -n "$SUB_A_PUB_1B" ]] || die "Day 1 VPC A public subnet 1b not found."
[[ -n "$SUB_B_PRV_1A" ]] || die "Day 1 VPC B private subnet not found."
[[ -n "$SG_WEB" ]] || die "Day 1 SG-WebPortal not found."
[[ -n "$SG_BASTION" ]] || die "Day 1 SG-BastionHost not found."

if [[ -z "$EC2_BASTION" ]]; then
  EC2_BASTION="$(aws ec2 describe-instances \
    --filters "Name=tag:Name,Values=$PROJECT-Bastion" \
              "Name=instance-state-name,Values=pending,running,stopping,stopped" \
    --query 'Reservations[0].Instances[0].InstanceId' --output text 2>/dev/null || true)"
  EC2_BASTION="$(first_or_empty "$EC2_BASTION")"
fi

if [[ -z "$EC2_WEB" ]]; then
  EC2_WEB="$(aws ec2 describe-instances \
    --filters "Name=tag:Name,Values=$PROJECT-WebPortal" \
              "Name=instance-state-name,Values=pending,running,stopping,stopped" \
    --query 'Reservations[0].Instances[0].InstanceId' --output text 2>/dev/null || true)"
  EC2_WEB="$(first_or_empty "$EC2_WEB")"
fi

if [[ -z "$EC2_INV" ]]; then
  EC2_INV="$(aws ec2 describe-instances \
    --filters "Name=tag:Name,Values=$PROJECT-Inventory" \
              "Name=instance-state-name,Values=pending,running,stopping,stopped" \
    --query 'Reservations[0].Instances[0].InstanceId' --output text 2>/dev/null || true)"
  EC2_INV="$(first_or_empty "$EC2_INV")"
fi

if [[ -z "$ALB_DNS" ]]; then
  ALB_DNS="$(aws elbv2 describe-load-balancers --names "$PROJECT-External-ALB" \
    --query 'LoadBalancers[0].DNSName' --output text 2>/dev/null || true)"
  ALB_DNS="$(first_or_empty "$ALB_DNS")"
fi

[[ -n "$EC2_BASTION" ]] || die "Day 1 Bastion instance not found."
[[ -n "$EC2_WEB" ]] || die "Day 1 Web Portal instance not found."
[[ -n "$EC2_INV" ]] || die "Day 1 Inventory instance not found."
[[ -n "$ALB_DNS" ]] || die "Day 1 External ALB not found."

record VPC_A "$VPC_A"
record VPC_B "$VPC_B"
record SUB_A_PUB_1A "$SUB_A_PUB_1A"
record SUB_A_PUB_1B "$SUB_A_PUB_1B"
record SUB_B_PRV_1A "$SUB_B_PRV_1A"
record SG_WEB "$SG_WEB"
record SG_BASTION "$SG_BASTION"
record EC2_BASTION "$EC2_BASTION"
record EC2_WEB "$EC2_WEB"
record EC2_INV "$EC2_INV"
record ALB_DNS "$ALB_DNS"

# ----------------------------------------------------------------------------
# Key lookup — compatible with the corrected Day 1 key-storage behavior.
# ----------------------------------------------------------------------------
KEY_FILE=""
for candidate in \
  "$HOME/.ssh/${KEY_NAME}.pem" \
  "$HOME/.swiftcart-keys/${KEY_NAME}.pem" \
  "$PWD/${KEY_NAME}.pem"; do
  if [[ -f "$candidate" ]]; then
    KEY_FILE="$candidate"
    break
  fi
done

if [[ "$DO_OS_MOUNTS" == "true" && ! -f "$KEY_FILE" ]]; then
  warn "Cannot find $KEY_NAME.pem; OS-level mounts will be skipped."
  warn "Checked: $HOME/.ssh, $HOME/.swiftcart-keys and current directory."
  DO_OS_MOUNTS="false"
fi

if [[ -n "$KEY_FILE" ]]; then
  chmod 400 "$KEY_FILE" 2>/dev/null || true
  log "SSH key: $KEY_FILE"
fi

# ----------------------------------------------------------------------------
# Step 2.1 — S3 static assets
# ----------------------------------------------------------------------------
log "Step 2.1 — S3 static-assets bucket"

if [[ -z "$S3_BUCKET" ]]; then
  S3_BUCKET="swiftcart-static-assets-${ACCOUNT_ID}"
fi

if ! aws s3api head-bucket --bucket "$S3_BUCKET" >/dev/null 2>&1; then
  aws s3api create-bucket --bucket "$S3_BUCKET" --region "$REGION" \
    --create-bucket-configuration LocationConstraint="$REGION"
  ok "Created S3 bucket: $S3_BUCKET"
else
  ok "S3 bucket already exists: $S3_BUCKET"
fi

aws s3api put-public-access-block --bucket "$S3_BUCKET" \
  --public-access-block-configuration \
  BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true

aws s3api put-bucket-encryption --bucket "$S3_BUCKET" \
  --server-side-encryption-configuration \
  '{"Rules":[{"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}'

aws s3api put-bucket-versioning --bucket "$S3_BUCKET" \
  --versioning-configuration Status=Enabled

cat > "$TMP_DIR/index.html" <<'HTML_CONTENT'
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>SwiftCart</title>
</head>
<body>
  <h1>SwiftCart Edge Content</h1>
  <p>Served from private S3 through CloudFront.</p>
</body>
</html>
HTML_CONTENT

aws s3 cp "$TMP_DIR/index.html" "s3://$S3_BUCKET/index.html" \
  --content-type text/html --cache-control 'public,max-age=300'

record S3_BUCKET "$S3_BUCKET"
ok "S3 ready: s3://$S3_BUCKET"

# ----------------------------------------------------------------------------
# Step 2.2 — CloudFront
# ----------------------------------------------------------------------------
log "Step 2.2 — CloudFront unified distribution"

CF_ID="${CF_ID:-}"
CF_ARN="${CF_ARN:-}"
CF_DOMAIN="${CF_DOMAIN:-}"
OAC_ID="${OAC_ID:-}"

if [[ "$SKIP_CLOUDFRONT" == "true" ]]; then
  warn "SKIP_CLOUDFRONT=true — CloudFront creation skipped by configuration."
else
  # CloudFront is global, so no --region flag is required here.
  if [[ -z "$OAC_ID" ]]; then
    OAC_ID="$(aws cloudfront list-origin-access-controls \
      --query "OriginAccessControlList.Items[?Name=='$PROJECT-OAC'].Id | [0]" \
      --output text 2>/dev/null || true)"
    OAC_ID="$(first_or_empty "$OAC_ID")"
  fi

  if [[ -z "$OAC_ID" ]]; then
    cat > "$TMP_DIR/oac.json" <<JSON_OAC
{
  "Name": "${PROJECT}-OAC",
  "Description": "SwiftCart private S3 origin access",
  "SigningProtocol": "sigv4",
  "SigningBehavior": "always",
  "OriginAccessControlOriginType": "s3"
}
JSON_OAC
    OAC_ID="$(aws cloudfront create-origin-access-control \
      --origin-access-control-config "file://$TMP_DIR/oac.json" \
      --query 'OriginAccessControl.Id' --output text)"
    ok "Created CloudFront OAC: $OAC_ID"
  else
    ok "CloudFront OAC already exists: $OAC_ID"
  fi
  record OAC_ID "$OAC_ID"

  if [[ -z "$CF_ID" ]]; then
    CF_ID="$(aws cloudfront list-distributions \
      --query "DistributionList.Items[?Comment=='$PROJECT-CDN'].Id | [0]" \
      --output text 2>/dev/null || true)"
    CF_ID="$(first_or_empty "$CF_ID")"
  fi

  if [[ -n "$CF_ID" ]]; then
    CF_JSON="$(aws cloudfront get-distribution --id "$CF_ID")"
    CF_ARN="$(jq -r '.Distribution.ARN // empty' <<<"$CF_JSON" 2>/dev/null || true)"
    CF_DOMAIN="$(jq -r '.Distribution.DomainName // empty' <<<"$CF_JSON" 2>/dev/null || true)"
    ok "CloudFront distribution already exists: $CF_ID"
  else
    CF_CONFIG="$TMP_DIR/cloudfront-distribution.json"
    CALLER_REFERENCE="${PROJECT}-${ACCOUNT_ID}-$(date +%s)"

    # Managed policies used by the original Day 2 design:
    #   CachingOptimized  = 658327ea-f89d-4fab-a63d-7e88639e58f6
    #   CachingDisabled   = 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
    #   AllViewer         = 216adef6-5c7f-47e4-b989-5492eafa07d3
    # IMPORTANT: CloudFront's AWS CLI model requires OriginSslProtocols to be an
    # object containing Quantity + Items. Build and validate the final JSON before
    # calling AWS so an old/stale config can never be submitted accidentally.
    cat > "$CF_CONFIG" <<JSON_CF
{
  "CallerReference": "$CALLER_REFERENCE",
  "Comment": "$PROJECT-CDN",
  "Enabled": true,
  "DefaultRootObject": "index.html",
  "PriceClass": "PriceClass_All",
  "HttpVersion": "http2and3",
  "IsIPV6Enabled": true,
  "Origins": {
    "Quantity": 2,
    "Items": [
      {
        "Id": "S3-$S3_BUCKET",
        "DomainName": "$S3_BUCKET.s3.$REGION.amazonaws.com",
        "OriginAccessControlId": "$OAC_ID",
        "S3OriginConfig": {
          "OriginAccessIdentity": ""
        }
      },
      {
        "Id": "ALB-$PROJECT",
        "DomainName": "$ALB_DNS",
        "CustomOriginConfig": {
          "HTTPPort": 80,
          "HTTPSPort": 443,
          "OriginProtocolPolicy": "http-only",
          "OriginSslProtocols": {
            "Quantity": 1,
            "Items": ["TLSv1.2"]
          },
          "OriginReadTimeout": 60,
          "OriginKeepaliveTimeout": 5
        }
      }
    ]
  },
  "DefaultCacheBehavior": {
    "TargetOriginId": "S3-$S3_BUCKET",
    "ViewerProtocolPolicy": "redirect-to-https",
    "AllowedMethods": {
      "Quantity": 2,
      "Items": ["GET", "HEAD"],
      "CachedMethods": {
        "Quantity": 2,
        "Items": ["GET", "HEAD"]
      }
    },
    "CachePolicyId": "658327ea-f89d-4fab-a63d-7e88639e58f6",
    "Compress": true
  },
  "CacheBehaviors": {
    "Quantity": 4,
    "Items": [
      {
        "PathPattern": "/api/*",
        "TargetOriginId": "ALB-$PROJECT",
        "ViewerProtocolPolicy": "redirect-to-https",
        "AllowedMethods": {
          "Quantity": 7,
          "Items": ["GET", "HEAD", "OPTIONS", "PUT", "POST", "PATCH", "DELETE"],
          "CachedMethods": {
            "Quantity": 2,
            "Items": ["GET", "HEAD"]
          }
        },
        "CachePolicyId": "4135ea2d-6df8-44a3-9df3-4b5a84be39ad",
        "OriginRequestPolicyId": "216adef6-5c7f-47e4-b989-5492eafa07d3",
        "Compress": true
      },
      {
        "PathPattern": "/checkout",
        "TargetOriginId": "ALB-$PROJECT",
        "ViewerProtocolPolicy": "redirect-to-https",
        "AllowedMethods": {
          "Quantity": 7,
          "Items": ["GET", "HEAD", "OPTIONS", "PUT", "POST", "PATCH", "DELETE"],
          "CachedMethods": {
            "Quantity": 2,
            "Items": ["GET", "HEAD"]
          }
        },
        "CachePolicyId": "4135ea2d-6df8-44a3-9df3-4b5a84be39ad",
        "OriginRequestPolicyId": "216adef6-5c7f-47e4-b989-5492eafa07d3",
        "Compress": true
      },
      {
        "PathPattern": "/product/*",
        "TargetOriginId": "ALB-$PROJECT",
        "ViewerProtocolPolicy": "redirect-to-https",
        "AllowedMethods": {
          "Quantity": 7,
          "Items": ["GET", "HEAD", "OPTIONS", "PUT", "POST", "PATCH", "DELETE"],
          "CachedMethods": {
            "Quantity": 2,
            "Items": ["GET", "HEAD"]
          }
        },
        "CachePolicyId": "4135ea2d-6df8-44a3-9df3-4b5a84be39ad",
        "OriginRequestPolicyId": "216adef6-5c7f-47e4-b989-5492eafa07d3",
        "Compress": true
      },
      {
        "PathPattern": "/health",
        "TargetOriginId": "ALB-$PROJECT",
        "ViewerProtocolPolicy": "redirect-to-https",
        "AllowedMethods": {
          "Quantity": 7,
          "Items": ["GET", "HEAD", "OPTIONS", "PUT", "POST", "PATCH", "DELETE"],
          "CachedMethods": {
            "Quantity": 2,
            "Items": ["GET", "HEAD"]
          }
        },
        "CachePolicyId": "4135ea2d-6df8-44a3-9df3-4b5a84be39ad",
        "OriginRequestPolicyId": "216adef6-5c7f-47e4-b989-5492eafa07d3",
        "Compress": true
      }
    ]
  },
  "Restrictions": {
    "GeoRestriction": {
      "RestrictionType": "none",
      "Quantity": 0
    }
  },
  "ViewerCertificate": {
    "CloudFrontDefaultCertificate": true,
    "MinimumProtocolVersion": "TLSv1.2_2021"
  }
}
JSON_CF

    # Validate the exact configuration that will be submitted.
    if ! jq -e '.Origins.Items[1].CustomOriginConfig.OriginSslProtocols |
        type == "object" and .Quantity == 1 and (.Items | type == "array") and .Items[0] == "TLSv1.2"' \
        "$CF_CONFIG" >/dev/null 2>&1; then
      echo "[FAIL] Invalid CloudFront JSON: OriginSslProtocols is not the required object shape." >&2
      jq '.Origins.Items[1].CustomOriginConfig.OriginSslProtocols' "$CF_CONFIG" >&2 || true
      die "CloudFront configuration validation failed before AWS API call."
    fi

    log "Creating CloudFront distribution..."
    set +e
    CF_OUTPUT="$(aws cloudfront create-distribution \
      --distribution-config "file://$CF_CONFIG" 2>&1)"
    CF_RC=$?
    set -e

    if [[ "$CF_RC" -ne 0 ]]; then
      if grep -qiE 'account must be verified|account.*verified|verify your account|account verification' <<<"$CF_OUTPUT"; then
        warn "AWS account verification is blocking CloudFront creation."
        warn "This is an AWS account-level restriction; changing IAM or the CLI command will not bypass it."
        warn "Continuing with S3, EFS and EBS so Day 2 does not fail halfway."
        CF_ID=""
        CF_ARN=""
        CF_DOMAIN=""
      else
        printf '%s\n' "$CF_OUTPUT" >&2
        die "CloudFront distribution creation failed."
      fi
    else
      if command -v jq >/dev/null 2>&1; then
        CF_ID="$(jq -r '.Distribution.Id // empty' <<<"$CF_OUTPUT")"
        CF_ARN="$(jq -r '.Distribution.ARN // empty' <<<"$CF_OUTPUT")"
        CF_DOMAIN="$(jq -r '.Distribution.DomainName // empty' <<<"$CF_OUTPUT")"
      else
        CF_ID="$(aws cloudfront list-distributions \
          --query "DistributionList.Items[?Comment=='$PROJECT-CDN'].Id | [0]" \
          --output text)"
        CF_ARN="$(aws cloudfront get-distribution --id "$CF_ID" --query 'Distribution.ARN' --output text)"
        CF_DOMAIN="$(aws cloudfront get-distribution --id "$CF_ID" --query 'Distribution.DomainName' --output text)"
      fi
      ok "CloudFront created: $CF_ID ($CF_DOMAIN)"
    fi
  fi
fi

record CF_ID "$CF_ID"
record CF_ARN "$CF_ARN"
record CF_DOMAIN "$CF_DOMAIN"

# Apply the CloudFront-only bucket policy only when CloudFront really exists.
# This is deliberately skipped during the AWS account-verification failure.
if [[ -n "$CF_ARN" ]]; then
  log "Applying private S3 bucket policy for CloudFront OAC"
  cat > "$TMP_DIR/s3-cloudfront-policy.json" <<JSON_POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "AllowCloudFrontServicePrincipalReadOnly",
      "Effect": "Allow",
      "Principal": {
        "Service": "cloudfront.amazonaws.com"
      },
      "Action": "s3:GetObject",
      "Resource": "arn:aws:s3:::$S3_BUCKET/*",
      "Condition": {
        "StringEquals": {
          "AWS:SourceArn": "$CF_ARN"
        }
      }
    }
  ]
}
JSON_POLICY
  aws s3api put-bucket-policy --bucket "$S3_BUCKET" \
    --policy "file://$TMP_DIR/s3-cloudfront-policy.json"
  ok "S3 policy locked to CloudFront distribution."
else
  warn "CloudFront ARN is empty; CloudFront-only S3 bucket policy is NOT applied yet."
fi

# ----------------------------------------------------------------------------
# Step 2.3 — EFS shared storage
# ----------------------------------------------------------------------------
log "Step 2.3 — EFS shared storage"

SG_EFS="${SG_EFS:-}"
EFS_ID="${EFS_ID:-}"

if [[ -z "$SG_EFS" ]]; then
  SG_EFS="$(aws ec2 describe-security-groups \
    --filters "Name=vpc-id,Values=$VPC_A" "Name=group-name,Values=SG-EFS-Mount" \
    --query 'SecurityGroups[0].GroupId' --output text 2>/dev/null || true)"
  SG_EFS="$(first_or_empty "$SG_EFS")"
fi

if [[ -z "$SG_EFS" ]]; then
  SG_EFS="$(aws ec2 create-security-group \
    --group-name SG-EFS-Mount \
    --description 'SwiftCart EFS NFS mount access from Web Portal' \
    --vpc-id "$VPC_A" \
    --tag-specifications "ResourceType=security-group,Tags=[{Key=Name,Value=SG-EFS-Mount},{Key=Project,Value=$PROJECT}]" \
    --query GroupId --output text)"
  ok "Created SG-EFS-Mount: $SG_EFS"
fi

# Duplicate-rule errors are intentionally ignored; the desired rule is idempotent.
aws ec2 authorize-security-group-ingress \
  --group-id "$SG_EFS" --protocol tcp --port 2049 --source-group "$SG_WEB" \
  >/dev/null 2>&1 || true

record SG_EFS "$SG_EFS"

if [[ -z "$EFS_ID" ]]; then
  EFS_ID="$(aws efs describe-file-systems \
    --query "FileSystems[?Name=='$PROJECT-Shared-Uploads'].FileSystemId | [0]" \
    --output text 2>/dev/null || true)"
  EFS_ID="$(first_or_empty "$EFS_ID")"
fi

if [[ -z "$EFS_ID" ]]; then
  EFS_ID="$(aws efs create-file-system \
    --region "$REGION" \
    --performance-mode generalPurpose \
    --throughput-mode bursting \
    --encrypted \
    --tags Key=Name,Value="$PROJECT-Shared-Uploads" Key=Project,Value="$PROJECT" \
    --query FileSystemId --output text)"
  wait_efs_available "$EFS_ID" || die "EFS $EFS_ID did not reach available state."
  ok "Created EFS: $EFS_ID"
else
  ok "EFS already exists: $EFS_ID"
fi

record EFS_ID "$EFS_ID"

create_mount_target() {
  local subnet="$1" az="$2" mt_id ip

  mt_id="$(aws efs describe-mount-targets --region "$REGION" --file-system-id "$EFS_ID" \
    --query "MountTargets[?SubnetId=='$subnet'].MountTargetId | [0]" \
    --output text 2>/dev/null || true)"
  mt_id="$(first_or_empty "$mt_id")"

  if [[ -n "$mt_id" ]]; then
    ok "EFS mount target already exists in $az: $mt_id"
  else
    mt_id="$(aws efs create-mount-target --region "$REGION" \
      --file-system-id "$EFS_ID" \
      --subnet-id "$subnet" \
      --security-groups "$SG_EFS" \
      --query MountTargetId --output text)"
    ok "Created EFS mount target in $az: $mt_id"
  fi

  wait_efs_mount_target_available "$mt_id" || die "EFS mount target $mt_id in $az did not become available."

  ip="$(aws efs describe-mount-targets --region "$REGION" --mount-target-id "$mt_id" \
    --query 'MountTargets[0].IpAddress' --output text)"
  ip="$(first_or_empty "$ip")"
  [[ -n "$ip" ]] || die "Could not determine EFS mount target IP for $mt_id ($az)."

  printf '%s|%s|%s\n' "$az" "$mt_id" "$ip"
}

EFS_MT_A1="$(create_mount_target "$SUB_A_PUB_1A" "$AZ1")"
EFS_MT_A2="$(create_mount_target "$SUB_A_PUB_1B" "$AZ2")"
EFS_MT_A1_ID="${EFS_MT_A1#*|}"; EFS_MT_A1_ID="${EFS_MT_A1_ID%%|*}"
EFS_MT_A1_IP="${EFS_MT_A1##*|}"
EFS_MT_A2_ID="${EFS_MT_A2#*|}"; EFS_MT_A2_ID="${EFS_MT_A2_ID%%|*}"
EFS_MT_A2_IP="${EFS_MT_A2##*|}"
record EFS_MT_A1_ID "$EFS_MT_A1_ID"
record EFS_MT_A1_IP "$EFS_MT_A1_IP"
record EFS_MT_A2_ID "$EFS_MT_A2_ID"
record EFS_MT_A2_IP "$EFS_MT_A2_IP"

log "EFS mount target AZ1 IP: $EFS_MT_A1_IP"
log "EFS mount target AZ2 IP: $EFS_MT_A2_IP"

# ----------------------------------------------------------------------------
# Step 2.4 — EBS gp3 cache for Inventory
# ----------------------------------------------------------------------------
log "Step 2.4 — EBS Inventory cache"

EBS_ID="${EBS_ID:-}"
INVENTORY_AZ="$(aws ec2 describe-instances --instance-ids "$EC2_INV" \
  --query 'Reservations[0].Instances[0].Placement.AvailabilityZone' --output text)"
INVENTORY_AZ="$(first_or_empty "$INVENTORY_AZ")"
[[ -n "$INVENTORY_AZ" ]] || die "Could not determine Inventory Availability Zone."

if [[ -z "$EBS_ID" ]]; then
  EBS_ID="$(aws ec2 describe-volumes \
    --filters "Name=tag:Name,Values=Inventory-Cache-DB" "Name=availability-zone,Values=$INVENTORY_AZ" \
    --query 'Volumes[?State!=`deleted`][0].VolumeId' --output text 2>/dev/null || true)"
  EBS_ID="$(first_or_empty "$EBS_ID")"
fi

if [[ -z "$EBS_ID" ]]; then
  EBS_ID="$(aws ec2 create-volume \
    --availability-zone "$INVENTORY_AZ" \
    --volume-type gp3 \
    --size 50 \
    --iops 3000 \
    --throughput 125 \
    --encrypted \
    --tag-specifications "ResourceType=volume,Tags=[{Key=Name,Value=Inventory-Cache-DB},{Key=Project,Value=$PROJECT}]" \
    --query VolumeId --output text)"
  wait_volume_state "$EBS_ID" available || die "EBS $EBS_ID did not reach available state."
  ok "Created EBS: $EBS_ID in $INVENTORY_AZ"
else
  ok "EBS already exists: $EBS_ID"
fi

ATTACHED_TO="$(aws ec2 describe-volumes --volume-ids "$EBS_ID" \
  --query 'Volumes[0].Attachments[0].InstanceId' --output text 2>/dev/null || true)"
ATTACHED_TO="$(first_or_empty "$ATTACHED_TO")"

if [[ -z "$ATTACHED_TO" ]]; then
  aws ec2 attach-volume --volume-id "$EBS_ID" --instance-id "$EC2_INV" --device /dev/sdf >/dev/null
  wait_volume_state "$EBS_ID" in-use || die "EBS $EBS_ID did not reach in-use state after attachment."
  ok "Attached EBS to Inventory: /dev/sdf (Nitro may expose it as NVMe)."
elif [[ "$ATTACHED_TO" == "$EC2_INV" ]]; then
  ok "EBS already attached to Inventory."
else
  die "EBS $EBS_ID is attached to another instance: $ATTACHED_TO"
fi

record INVENTORY_AZ "$INVENTORY_AZ"
record EBS_ID "$EBS_ID"

# ----------------------------------------------------------------------------
# Step 3 — OS-level mounts through Bastion
# ----------------------------------------------------------------------------
if [[ "$DO_OS_MOUNTS" == "true" ]]; then
  command -v ssh >/dev/null 2>&1 || die "ssh is required for OS-level mounts."

  instance_field() {
    local instance="$1" field="$2"
    aws ec2 describe-instances --instance-ids "$instance" \
      --query "Reservations[0].Instances[0].$field" --output text
  }

  BASTION_PUBLIC_IP="$(instance_field "$EC2_BASTION" PublicIpAddress)"
  WEB_PRIVATE_IP="$(instance_field "$EC2_WEB" PrivateIpAddress)"
  INV_PRIVATE_IP="$(instance_field "$EC2_INV" PrivateIpAddress)"
  WEB_AZ="$(instance_field "$EC2_WEB" Placement.AvailabilityZone)"
  BASTION_PUBLIC_IP="$(first_or_empty "$BASTION_PUBLIC_IP")"
  WEB_PRIVATE_IP="$(first_or_empty "$WEB_PRIVATE_IP")"
  INV_PRIVATE_IP="$(first_or_empty "$INV_PRIVATE_IP")"
  WEB_AZ="$(first_or_empty "$WEB_AZ")"

  [[ -n "$BASTION_PUBLIC_IP" ]] || die "Bastion has no public IP."
  [[ -n "$WEB_PRIVATE_IP" ]] || die "Web Portal private IP not found."
  [[ -n "$INV_PRIVATE_IP" ]] || die "Inventory private IP not found."
  [[ -n "$WEB_AZ" ]] || die "Web Portal Availability Zone not found."

  if [[ "$WEB_AZ" == "$AZ1" ]]; then
    EFS_WEB_IP="$EFS_MT_A1_IP"
  elif [[ "$WEB_AZ" == "$AZ2" ]]; then
    EFS_WEB_IP="$EFS_MT_A2_IP"
  else
    die "Web Portal is in unsupported AZ $WEB_AZ; expected $AZ1 or $AZ2."
  fi
  log "Web Portal is in $WEB_AZ; using EFS mount target IP $EFS_WEB_IP"

  record BASTION_PUBLIC_IP "$BASTION_PUBLIC_IP"
  record WEB_PRIVATE_IP "$WEB_PRIVATE_IP"
  record INV_PRIVATE_IP "$INV_PRIVATE_IP"

  SSH_PROXY="ssh -i '$KEY_FILE' -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -W %h:%p ec2-user@$BASTION_PUBLIC_IP"

  log "Mounting EFS on Web Portal via Bastion"
  ssh -i "$KEY_FILE" \
    -o StrictHostKeyChecking=no \
    -o UserKnownHostsFile=/dev/null \
    -o ConnectTimeout=20 \
    -o ProxyCommand="$SSH_PROXY" \
    "ec2-user@$WEB_PRIVATE_IP" 'bash -s' <<REMOTE_WEB
set -Eeuo pipefail
sudo yum install -y amazon-efs-utils >/dev/null 2>&1 || true
sudo mkdir -p /var/www/swiftcart/shared_uploads
sudo chmod 775 /var/www/swiftcart/shared_uploads

if ! mountpoint -q /var/www/swiftcart/shared_uploads; then
  sudo sed -i '\# /var/www/swiftcart/shared_uploads #d' /etc/fstab
  printf '%s\n' "$EFS_ID:/ /var/www/swiftcart/shared_uploads efs _netdev,tls,mounttargetip=$EFS_WEB_IP 0 0" | sudo tee -a /etc/fstab >/dev/null
  sudo mount -t efs -o tls,mounttargetip=$EFS_WEB_IP "$EFS_ID:/" /var/www/swiftcart/shared_uploads
fi

mountpoint -q /var/www/swiftcart/shared_uploads
sudo chown -R ec2-user:ec2-user /var/www/swiftcart/shared_uploads || true
printf 'EFS_MOUNT_OK %s\n' "$(df -h /var/www/swiftcart/shared_uploads | tail -1)"
REMOTE_WEB
  ok "EFS mounted at /var/www/swiftcart/shared_uploads"

  log "Mounting gp3 EBS on Inventory via Bastion"
  ssh -i "$KEY_FILE" \
    -o StrictHostKeyChecking=no \
    -o UserKnownHostsFile=/dev/null \
    -o ConnectTimeout=20 \
    -o ProxyCommand="$SSH_PROXY" \
    "ec2-user@$INV_PRIVATE_IP" 'bash -s' <<'REMOTE_INV'
set -Eeuo pipefail
sudo mkdir -p /mnt/inventory_cache

DEVICE=""
for _ in $(seq 1 30); do
  DEVICE="$(lsblk -dnbo NAME,SIZE,TYPE | awk '$3=="disk" && $2 >= 49000000000 && $2 <= 55000000000 {print "/dev/"$1; exit}')"
  [[ -n "$DEVICE" ]] && break
  sleep 2
done

[[ -n "$DEVICE" ]] || { echo "Could not find the 50-GiB EBS disk." >&2; exit 1; }

if ! sudo blkid "$DEVICE" >/dev/null 2>&1; then
  sudo mkfs.xfs -f "$DEVICE"
fi

UUID="$(sudo blkid -s UUID -o value "$DEVICE")"
[[ -n "$UUID" ]] || { echo "Could not read filesystem UUID." >&2; exit 1; }

sudo sed -i '\# /mnt/inventory_cache #d' /etc/fstab
printf 'UUID=%s /mnt/inventory_cache xfs defaults,nofail 0 2\n' "$UUID" | sudo tee -a /etc/fstab >/dev/null

if ! mountpoint -q /mnt/inventory_cache; then
  sudo mount /mnt/inventory_cache
fi

mountpoint -q /mnt/inventory_cache
sudo chown -R ec2-user:ec2-user /mnt/inventory_cache || true
printf 'EBS_MOUNT_OK %s %s\n' "$DEVICE" "$(df -h /mnt/inventory_cache | tail -1)"
REMOTE_INV
  ok "EBS mounted at /mnt/inventory_cache"
else
  warn "DO_OS_MOUNTS=false — skipping Linux mount operations."
fi

# ----------------------------------------------------------------------------
# Optional CloudFront wait
# ----------------------------------------------------------------------------
if [[ -n "$CF_ID" && "$WAIT_CLOUDFRONT" == "true" ]]; then
  log "Waiting for CloudFront deployment..."
  wait_cloudfront_deployed "$CF_ID" || die "CloudFront $CF_ID did not reach Deployed state within the wait window."
  ok "CloudFront deployment completed."
fi

# ----------------------------------------------------------------------------
# Final validation
# ----------------------------------------------------------------------------
log "Final validation"
aws s3api head-bucket --bucket "$S3_BUCKET"
aws efs describe-file-systems --file-system-id "$EFS_ID" \
  --query 'FileSystems[0].[FileSystemId,State,Encrypted]' --output table
aws ec2 describe-volumes --volume-ids "$EBS_ID" \
  --query 'Volumes[0].[VolumeId,State,Size,VolumeType,Iops,Throughput,AvailabilityZone]' \
  --output table

if [[ -n "$CF_ID" ]]; then
  aws cloudfront get-distribution --id "$CF_ID" \
    --query 'Distribution.[Id,Status,DomainName,ARN]' --output table
fi

record COMPLETE true

cat <<SUMMARY

================================================================================
 SwiftCart — Day 2 Summary
================================================================================
 Region            : $REGION
 Account           : $ACCOUNT_ID
 S3 bucket         : $S3_BUCKET
 CloudFront ID     : ${CF_ID:-NOT CREATED}
 CloudFront domain : ${CF_DOMAIN:-NOT CREATED}
 ALB origin        : $ALB_DNS
 EFS ID            : $EFS_ID
 EFS mount targets : $AZ1 + $AZ2
 EBS volume        : $EBS_ID
 EBS AZ            : $INVENTORY_AZ
 EBS spec          : 50 GiB gp3 / 3000 IOPS / 125 MB/s
 OS mounts         : $DO_OS_MOUNTS
 State file        : $STATE_FILE
================================================================================
SUMMARY

if [[ -z "$CF_ID" ]]; then
  cat <<'NEXT'

CloudFront is still pending because AWS account verification prevented
CreateDistribution.

After AWS verifies the account, simply rerun this same script:

  ./swiftcart-day2-provision-ap-southeast-2-fixed-v8.sh

The script is idempotent: it will reuse the S3/EFS/EBS resources and create the
missing CloudFront distribution, then apply the CloudFront-only S3 bucket policy.
NEXT
else
  cat <<NEXT

CloudFront URL:
  https://$CF_DOMAIN/index.html

API test:
  curl https://$CF_DOMAIN/api/v1/inventory/SKU-1001

Checkout test:
  curl -X POST "https://$CF_DOMAIN/checkout" \\
    -H 'Content-Type: application/json' \\
    -d '{"sku":"SKU-1001","quantity":2,"email":"test@example.com"}'
NEXT
fi
